### ISSUE TITLE
How can I install this in Github Enterprise?

### ISSUE THREAD

**Issue by sinharitika07** [stilliard/github-task-list-completed#14]
How can I install this in Github Enterprise?

**Comment by stilliard** [comment]
Hi @sinharitika07 
I have no idea sorry, I assume it'd install like any other app in github enterprise but I've never used the enterprise version.

**Comment by stilliard** [comment]
Let me know if you find there's special install instructions for enterprise btw. 
Any additional notes would be good to offer these back out to other users, thank you.
