### ISSUE TITLE
If there was a way to show the unchecked tasks in the report

### ISSUE THREAD

**Issue by pravic** [stilliard/github-task-list-completed#16]
Right now, the details report shows:

> 1 / 3 tasks completed
> 2 tasks still to be completed

It would be helpful to build a list of links to those comments. For example,

| Uncompleted tasks |
| ---- |
| * [ ] [A test checkbox](https://github.com/stilliard/github-task-list-completed/issues/16#issuecomment-768411586)
| * [ ] Another checkbox

**Comment by pravic** [comment]
Some text in a comment 

* [ ] A test checkbox

More text

**Comment by billsacks** [comment]
I agree this would be useful. In the meantime, though, I'll make a shameless plug for this command-line tool that I developed for this purpose: https://github.com/ESMCI/github-tools (see the gh-pr-query usage in the README). I personally have been using task-list-completed for a quick count in conjunction with that command-line tool to see a consolidated list of outstanding (or completed) tasks in a PR.

**Comment by stilliard** [comment]
This feature is now live! Sorry it's been on the back burner for a while. 
![image](https://github.com/stilliard/github-task-list-completed/assets/77454/0c3bccf5-91a4-4b85-91c9-55fefbaca74a)

**Comment by billsacks** [comment]
This is awesome, @stilliard - thank you for adding this feature!
