### ISSUE TITLE
Delay / order of execution

### ISSUE THREAD

**Issue by mariusjp** [stilliard/github-task-list-completed#17]
We are using a Github action to add a comment to a new PR to create a checklist for our developers/reviewers to "enforce" a bit of strict thinking / handling of PRs.

But on a fresh PR your check runs "too soon" and says "0/0 tasks completed", because the comment still needs to be added.
To clarify, by adding comments this application reruns perfectly.
_But_ somehow the timing sometimes is so "perfect" that the task-list check won't run again.

Would it be possible to configure it to wait:
- A set time
- For a specific other task to finish

**Comment by stilliard** [comment]
Hey @MJTheOne 
Ah interesting, as a temp solution could you add the delay to your action instead?

**Comment by mariusjp** [comment]
Hey @stilliard!
Btw thanks for a very nice app!
Stupid that I didn't think of that haha. I actually mention that your app perfectly responds to new comments.
I guess I could make that work!

Thanks for your quick reply!

**Comment by stilliard** [comment]
Aha no worries, I think it'd be a good addition anyway btw. 

Atm we don't have a generic config file added, on my todolist for the project but once we do we could consider adding delays or waiting for other tasks too. 

Hope your action delay works well for you :+1:
