### ISSUE TITLE
Include tasks in comments as well?

### ISSUE THREAD

**Issue by soberman** [stilliard/github-task-list-completed#2]
Hi! Thank you for your work on this!
Could you please extend it to take tasks inside of the comments in the pull request into account as well? That would greatly increase the workflow: in order to not miss important changes to the code we could make a comment and include there a checkbox with something like "rewrite with bar-foo". This would disallow the PR merge until that task is completed inside of the comment, which makes it way easier to keep track of the code change tasks.

Thanks!

**Comment by stilliard** [comment]
Thanks @soberman , I love that idea & I'll see what I can do

**Comment by soberman** [comment]
Awesome, thank you!

**Comment by soberman** [comment]
Any luck on implementing it so far?

**Comment by soberman** [comment]
Hi! Any progress on this one?

**Comment by stilliard** [comment]
Hi @soberman ,
I've been away for the past few weeks but back now. 
I've not had chance to look at adding this but if you're interested please feel free to fork the app and try for yourself, thanks :)

**Comment by hjkatz** [comment]
Hello! I'd like to try and implement this feature however I'm having trouble getting set up with glitch and seeing the app working for my personal repos. Adding this feature should be quick and straightforward and I would like to help if possible.

**Comment by stilliard** [comment]
Hi @hjkatz 
Good timing as I'm currently away and had some free time earlier today to play around with this idea. 
Ref glitch, check out the logs in glitch as they always help me when getting set up.

I've submitted a PR #15 for this as a preview & when I'm back next week I'll be looking to merge it :)

**Comment by hjkatz** [comment]
👋  So I actually got glitch working and started working on a PR myself too haha. Would you like any collaboration on PR#15? If not I'm fine just waiting and helping however :)

To see my glitchy playing around I've got this so far: https://glitch.com/edit/#!/candy-lucky-meat

I got to the point where I realized that I actually want to view the whole PR, comments, review comments, and issue comments all at the same time to ensure there's not a "Well if this one comment has all tasks completed", then the whole check is a success sort of thing, but then I started thinking about app state and got distracted.

**Comment by stilliard** [comment]
:wave: Aha sorry I should have updated the issue earlier about me working on it *finally*.
Checked out your code and it looks great, looks like we took a pretty similar approach using pull_request_review_comment event & abstracting hasOutstandingTasks().

Think mines all done now but thank you anyway for the offer. Actually if you like you could have a look over mine to see what you think.
Will be back next week, hopefully can get it released then, don't wanna release it while I'm away in case there's a bug I wont be available to resolve it as fast lol.

**Comment by stilliard** [comment]
This feature is now live :zap:
