### ISSUE TITLE
Optional tasks

### ISSUE THREAD

**Issue by GLJeffery** [stilliard/github-task-list-completed#21]
Is it possible to mark some tasks as optional? So that only required ones let the check pass and some can be left unchecked

**Comment by coler-j** [comment]
Can't you just delete them in the PR description?

**Comment by stilliard** [comment]
@GLJeffery 
Sorry for the delay on this, I thought I'd replied before but must not have hit send. 

@coler-j Yeah deleting them works, or crossing them out with ~~- [ ] todo~~

I actually really like this idea btw though, currently we have another github bot we built that adds comments with todo's for adding docs based on the files you edit. Sometimes though those are more optional as a file change doesn't always mean docs need updates so some sort of optional feature might be interesting. 

Maybe optional tickboxes have some symbol (not already used in markdown) to indicate this, or maybe they should be prefixed with [OPTIONAL] or similar?

**Comment by coler-j** [comment]
`[ ] [OPTIONAL] The task description` might be nice.

**Comment by stilliard** [comment]
Cool, I think that's probably best too. 
Super clear to the user and to the bot.

**Comment by GLJeffery** [comment]
> Can't you just delete them in the PR description?

we could, deleting/crossing out feels more active than automated though, and if a user deleted tasks, it could also be a way to bypass the bot if it gets missed that the task isn't there (we'd have to rely on reviewers checking that necessary tasks were kept in the list)

for our use case we have a generic template with a checklist that gets applied to all PRs, not all are always applicable to each PR depending on the type of work (UI vs API, etc), we'll ask for different actionables, with about half of them required for all PRs (linting for ex)

**Comment by stilliard** [comment]
I've pushed a new version which includes support for both optional and skippable tasks. 
Tasks with OPTIONAL in the text (case sensitive) will now be optional, counted only if ticked and a count of remaining optional tasks is added to the check text (if any are present). Further info in the readme. 
Hope this helps.
