### ISSUE TITLE
Blocking based on PR feedback

### ISSUE THREAD

**Issue by ebridges** [stilliard/github-task-list-completed#22]
I was wondering if this tool would be appropriate for a specific use case.  We'd like to be able to block merging a pull request if there are tasks that have been added by a reviewer of a pull request.  

Does this scan PR comments for tasks?  If not, would it be difficult to add it?  If you're open to PRs, we would be happy to attempt it, or perhaps even sponsor for it.

Thank you

**Comment by stilliard** [comment]
Hey @ebridges 
We sure do, we scan the PR body, comments, review comments & review diff level comments.

**Comment by ebridges** [comment]
Awesome thanks a lot!
