### ISSUE TITLE
Can't require tasks to be complete before it can be merged

### ISSUE THREAD

**Issue by eelior** [stilliard/github-task-list-completed#23]
Hey, love the idea of this app really :)

I installed the app and enabled it in al repos, then I tried to follow the docs to add it to the rules but couldn't find it there.

The docs: 
```
Want to require tasks to be complete before it can be merged?

Inside your GitHub repo > Settings > Branches > Branch protection rules > Add rule > select require checks & require this check to pass.
```

My repo settings:

![](https://i.ibb.co/XpjG1wz/image-7.png)

**Comment by stilliard** [comment]
Hi @eelior 
Might be it only shows up after a new PR is made. 
Try submitting a PR to your repo to see if github then shows it through here on the settings.

**Comment by eelior** [comment]
It worked out :) thx!
