### ISSUE TITLE
Task list check should have some type of timeout or logic to stop checking if PR is closed

### ISSUE THREAD

**Issue by rhanton** [stilliard/github-task-list-completed#28]
I noticed that if you apply this app to a repository, then do NOT set task-list-completed as a status check required for merge, and then run a pull request with a task list, but do NOT check the checkboxes before merging - this can keep the code looping forever looking for those check-boxes to be checked.

A secondary issue with this seems to be that because the server is busy checking against those boxes (that may never be checked because the PR is now closed) - it then becomes impossible to add "task-list-complted" to the required status checks for a branch because it's busy spinning its wheels. The only way to stop this runaway loop is to go back to the PR and check all the checkboxes. This seems to indicate that some type of timeout may be needed or at very least a check of whether the PR is already closed or not.

**Steps to recreate:**
1. Apply app to a repository (do not set up status check required for merge).
2. Create a new pull request with a task list in it.
3. When the build runs, the app will start checking that all 0/N tasks are checked. Check none of them.
4. Watch as the app runs - waiting for checkboxes to be checked for hours or days.
5. Close that PR - the app will continue running, waiting for the checkboxes to be checked forever.

**Comment by stilliard** [comment]
Hi @rhanton 
Glad you're interested in how the app works, I can clarify that though in GitHub it looks like its constantly checking your PR, it's actually only checked on open and on change. 
There's no constantly running loop started for your PR and so no need for a timeout etc. 
You can find out more here in the index.js file which shows how GitHub sends us each request/event and we treat them as new each time: https://github.com/stilliard/github-task-list-completed/blob/master/index.js

**Comment by NiallBegley** [comment]
Sorry to reopen this, but I'm seeing this same behavior and I think its more than just an appearance thing.

I noticed that when I first started trying out this app it worked as intended with both checklists in the main PR description as well as checklists that I was adding via comments posted by the github actions bot.  But then after closing the PR and opening new ones as tests, the app stopped behaving correctly and `task-list-completed` remains running in the checks tab.  For example, here's the app running on a freshly opened PR (certainly newer than 1.5 hours):

<img width="385" alt="image" src="https://user-images.githubusercontent.com/6789600/181768757-1412ce88-b6a8-4c62-8c10-2baad1b77d2c.png">

That hangs around even after the app is removed from my organization.

Additionally, when it gets into this state it doesn't seem to recognize when the checklists get completed

<img width="1033" alt="Screen Shot 2022-07-29 at 9 19 12 AM" src="https://user-images.githubusercontent.com/6789600/181769210-442cac61-628b-462b-aebf-1687596784db.png">

**Comment by stilliard** [comment]
Hi @NiallBegley 
I can assure you, ref https://github.com/stilliard/github-task-list-completed/blob/master/index.js the visual indicator of it being in progress is just that :) 
Github does sometimes take a while to update so you may see some checklist updates take a while but sometimes just updating the pr in some way tells github to recheck and that can help resolve it faster. 
Hope this helps.
