### ISSUE TITLE
GitHub Repo Settings - Branch protection rules

### ISSUE THREAD

**Issue by sanamumtaz** [stilliard/github-task-list-completed#29]
Following is mentioned in the READ.ME.md
`Inside your GitHub repo > Settings > Branches > Branch protection rules > Add rule > select require checks & require this check to pass.`
I do not see this rule in the settings. Has GitHub removed this rule?

**Comment by stilliard** [comment]
Hi,
The rule may not show if there's not been a pull request since adding the
app.
You could try adding a test pull request to force GitHub to check it and
then it should show.
Hope that helps.

**Comment by sanamumtaz** [comment]
Thanks for the help.
