### ISSUE TITLE
Support for Renovate bot

### ISSUE THREAD

**Issue by lukasjuhas** [stilliard/github-task-list-completed#32]
Thanks for the great package. 

It's currently missing support for @renovatebot, which is widely used to maintain dependencies. It uses checkboxes in order to trigger re-basing. This means that any PR that is created by @renovatebot will have pending checks when using this package.

Example of renovate PR:
<img width="918" alt="Screenshot 2022-12-16 at 14 52 48" src="https://user-images.githubusercontent.com/5247674/208180047-081f6a95-eb9c-49d2-a101-0b684a5a5182.png">

I've submitted a proposed a fix in a PR #31

**Comment by lukasjuhas** [comment]
It would be great to know whether we could merge the support for this or whether we need to publish a fork. Thanks, @stilliard !

**Comment by stilliard** [comment]
Hi @lukasjuhas 
Thanks for this PR, just taking a look now.
