### ISSUE TITLE
add option to exclude tasks from comments

### ISSUE THREAD

**Issue by szamanr** [stilliard/github-task-list-completed#33]
## problem

we use a [linear](https://linear.app) integration, which creates a new comment with the link to a linear issues linked to this PR. the link expands and shows the issue description, which may or may not contain checkboxes.

these checkboxes may or may not be relevant to the PR. for example, we use a bug template, where you check certain things like "does this issue affect >3 customers". so we often have tickets with unchecked checkboxed and that's expected.

the problem is, github-task-list-completed considers these checkboxes as part of the PR and won't succeed until you check them. this is creating a blocker where we cannot use this extension to ensure actual PR tasks are done.

## solution

add a setting "ignore checkboxes in comments". when on, only the PR description should be scanned.

**Comment by stilliard** [comment]
@szamanr Getting back to some of these issues, sorry it's been on the back burner for a while. 

I have a possible solution to this, what if we just ignore these comments from linear? Do you know the name of it's bot that adds these comments? I can add it to a list of ignored bots. 

Thanks

**Comment by szamanr** [comment]
@stilliard name is `linear`, https://github.com/apps/linear

**Comment by stilliard** [comment]
Thanks @szamanr , I'll have a look into that now to get it's comments ignored from the checks.

**Comment by stilliard** [comment]
Hey, this is now live. I've tested locally where I can but could you verify with a comment from linear please when you're free. 
Let me know if there's any issues, thanks

**Comment by szamanr** [comment]
looks like it's working, thanks!

**Comment by stilliard** [comment]
Awesome! Glad to hear :+1:
