### ISSUE TITLE
New github tasklist beta support

### ISSUE THREAD

**Issue by vwnj84** [stilliard/github-task-list-completed#35]
I've got a repo rule in place which runs a workflow. This workflow in turn calls an action which is reading a JSON-formatted file, dynamically creating issues for the PR and then updating the body of the PR with a tasklist built from the issues created. The repo rule also has github-task-list-completed as a mandatory check.

What I'd like to be able to do is the use github-task-list-completed app to block merging until this generated tasklist has been completed. I've tried a few things such as setting a label on the PR, re-running all checks, etc. It just doesn't seem to run again after it runs the first time and says '0/0 tasks'.

Unfortunately, since the original body of the PR may or may not have a tasklist, the check passes, and is not run again when the body of the PR is updated. I need the generated list, and it is not likely that a PR Template is going to be a viable solution, so I'm kind of stuck with a 'post-PR-creation' bit if hackery.

What can I do here?

**Comment by stilliard** [comment]
Hey @vwnj84 

Checks should run again on each update to the body, labels etc. But, there can be a delay especially if github's busy. 

Tested on one of my repos and ticking everything so it's successful and then unticking again un-marks the check as successful back to in progress. 

One other option is you could try self hosting the check. You could also modify the check here as needed. 
I don't have any docs on hosting atm sorry but the project uses probot and here's a link to their docs about deploying it: https://probot.github.io/docs/deployment/

Hope this helps.

**Comment by vwnj84** [comment]
I have figured it out. The app doesn't seem to work with GH's newer [tasklist](https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist) format, which is more an issue with marked than with your code.

```
``` [tasklist]
## This is a tasklist
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
```

I couldn't get GH to render the last line properly, but it is three back-tics.

**Comment by stilliard** [comment]
Ah interesting, admittedly I've not tried the new tasklists out yet as my Pr templates are automated with the old format. 

I wonder if marked sees them inside those blocks as a code block instead. 
Will try updating marked later and see if that resolves it. 
If not, maybe we parse for the ` ``` [tasklist] ` and strip that off as well as it's closing ` ``` ` before passing it to marked so it's essentially just treated like the old format task lists.

**Comment by vwnj84** [comment]
I think the code can be updated to work like you mentioned. The thing that it's not going to do is deal with the wonky behavior GH has around linked issues in the tasks. I've described it in full as a [feature request](https://github.com/orgs/community/discussions/39106?sort=old#discussioncomment-7209641) for tasklists.

**Comment by stilliard** [comment]
That would work great if they can implement it. 
The alternative I guess would be we'd need to loop through the tasklist items, checking each related issue to see if it's closed or not. 
I'll rename this issue to new tasklist beta support, for now and wait to see if there's any replies from github on your feature request.

**Comment by stilliard** [comment]
Looks like GitHub are pausing the current iteration of the new tasklist beta to re-think it, ref https://github.com/orgs/community/discussions/39106?sort=old#discussioncomment-7532593

Will be interesting to see their new ideas, I wonder if they'd be better off adding powers to the existing simple markdown checklists but will wait to see what they come up with.

**Comment by vwnj84** [comment]
Yup, it's dead. Saw that this morning. Thanks for thinking of this.

On Tue, Nov 14, 2023 at 6:07 PM Andrew Stilliard ***@***.***>
wrote:

> Looks like GitHub are pausing the current iteration of the new tasklist
> beta to re-think it, ref
> https://github.com/orgs/community/discussions/39106?sort=old#discussioncomment-7532593
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_orgs_community_discussions_39106-3Fsort-3Dold-23discussioncomment-2D7532593&d=DwMFaQ&c=q3cDpHe1hF8lXU5EFjNM_C93KOmcBXCBnhee2v6PYlc&r=cUr0o83CpaK3TPWh9J5dFcVhOqmlXSDlw-xSPPRrEcmyb7WZRzA5JOXGO0mQnEtI&m=hnHxp0Rdgf4HWtJvFphAoTlcrMCpGmOM1WBiwue73Obo_4Sv11qpG2E7rm3QhgOz&s=7rmo2cjbBy4St5kOZv2Go1pJMAwIANyXWYY9-k2dqcU&e=>
>
> Will be interesting to see their new ideas, I wonder if they'd be better
> off adding powers to the existing simple markdown checklists but will wait
> to see what they come up with.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_stilliard_github-2Dtask-2Dlist-2Dcompleted_issues_35-23issuecomment-2D1811534880&d=DwMFaQ&c=q3cDpHe1hF8lXU5EFjNM_C93KOmcBXCBnhee2v6PYlc&r=cUr0o83CpaK3TPWh9J5dFcVhOqmlXSDlw-xSPPRrEcmyb7WZRzA5JOXGO0mQnEtI&m=hnHxp0Rdgf4HWtJvFphAoTlcrMCpGmOM1WBiwue73Obo_4Sv11qpG2E7rm3QhgOz&s=lI5LLKRLqeVMwReCOaQr8hoPPCPuQm8otq2YqMVwrVc&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AS5EL3QP3MCWXUXAVCFCC4LYEP2UDAVCNFSM6AAAAAA5TENQ7CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJRGUZTIOBYGA&d=DwMFaQ&c=q3cDpHe1hF8lXU5EFjNM_C93KOmcBXCBnhee2v6PYlc&r=cUr0o83CpaK3TPWh9J5dFcVhOqmlXSDlw-xSPPRrEcmyb7WZRzA5JOXGO0mQnEtI&m=hnHxp0Rdgf4HWtJvFphAoTlcrMCpGmOM1WBiwue73Obo_4Sv11qpG2E7rm3QhgOz&s=hAgjMGJKFXsTHwB6zC62Uh74QtbT41mU_y5Falr4os8&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Mitch

-- 


*For more information on how and why we collect your personal 
information, please visit our Privacy Policy 
<https://www.motorolasolutions.com/en_us/about/privacy-policy.html?elqTrackId=8980d888905940e39a2613a7a3dcb0a7&elqaid=2786&elqat=2#privacystatement>.*
