### ISSUE TITLE
Task list checked failing rather than being in progress.

### ISSUE THREAD

**Issue by kevinfalconer-seccl** [stilliard/github-task-list-completed#36]
Thanks for the great work on the tool so far!

I was wondering what support there was for the option of the status check for `Task list completed` being in a failed state rather than always being in progress? We're a bit concerned with the potential costs of a status check always being in the `in progress` state for all open pull requests that have not pull completed their checklists.

**Comment by stilliard** [comment]
Hi @kevinfalconer-seccl 

This is a free app so no costs for the checks. 
Behind the scenes it's not actually constantly in progress, we report back to the PR via the api that the check is in progress each time it's updated until the checklist is completed, but there's no actual code constantly checking it, checks only run on a webhook from github when updates come in. 
Hope this helps.
