### ISSUE TITLE
Not possible to plug the check

### ISSUE THREAD

**Issue by pylapp** [stilliard/github-task-list-completed#37]
Hi!

I tried to use the **task-list-completed** product from the [GitHub Apps](https://github.com/apps/task-list-completed), but failed to configure it.
I also tried to install it through the [marketplace](https://github.com/marketplace/task-list-completed) with a free plan for [my organization](https://github.com/Orange-OpenSource), but failed to add status check for a pull request.

Indeed, when I try to define a new ruleset for a branch, the **task-list-completed** is never suggested.

Thus, I would like to know what things I missed and how I can configure the tool for [my project](https://github.com/Orange-OpenSource/ouds-ios). I read the documention in the README bu I think something is not enough accurate for me or has been a bit broken with new GitHub rules management.

Thank you a lot for your help!

<img width="300" alt="Capture d’écran 2024-07-16 à 13 43 22" src="https://github.com/user-attachments/assets/12bc4d07-23d6-4fd8-bd55-19076ce8ec49">

**Comment by stilliard** [comment]
Hi @pylapp,

In your screenshot, it looks like `task-list-completed` is already listed under the "Status checks that are required" no?

After saving with that set, if you open a new pull request to merge into the branch you've set this rule on, does the check not show at the bottom with any other checks?

**Comment by stilliard** [comment]
If the pull requests already exist btw, updating them in some way such as by editing the title, or checking/unchecking one of the checkboxes should trigger new checks to run. 
Hope this helps.

**Comment by pylapp** [comment]
I tried to define a new rule for the branch, but this GitHub feature is not able to find the task-list-completed stuff even if I freshly installed it again.

For example for classic branch rule management bellow:
![Capture d’écran 2024-07-16 à 16 24 06](https://github.com/user-attachments/assets/9cd2e2eb-a580-426c-be8e-499dda76d7cb)

And below the new ruleset feature:
![Capture d’écran 2024-07-16 à 16 23 15](https://github.com/user-attachments/assets/3b7f7514-cd2b-4485-b74d-b427aa49c436)

It seems task-list-completed cannot be find O_ô

**Comment by pylapp** [comment]
@stilliard Ok that's quite strange, I don't know what happen but it seems the situaiton has been solved a bit by pushing new commits on the branch or changing its branch state.
It seems the GitHub app I installed is running (because I don't have any service pluged otherwise as ruleset).
Quite strange, is it possible there might be some delay because of GitHub sending statuses to your service?

**Comment by stilliard** [comment]
Hi @pylapp 
Glad that's working for you now. 
With the branch rule setup etc. that's all with Github, we only get notified for changes on pull requests such as new pr's or updates to their titles, changes in the description, comments and when new commits are pushed.

**Comment by pylapp** [comment]
So what do you suggest? I fail to define rulesets calling task-list-completed (the text you saw in a previsous screenshot was jsut a name I gave).
Should we still use task-list-completed with the GitHub App integration? There is no mention of this solution in the documentation (only integration through marketplace).

**Comment by stilliard** [comment]
Hi @pylapp 
Sorry I think I've misunderstood, does it not work for you atm?

**Comment by stilliard** [comment]
I've checked on the repo you liked and it seems to have worked correctly:

Ref this recently merged PR: https://github.com/Orange-OpenSource/ouds-ios/pull/48
![image](https://github.com/user-attachments/assets/f94b6720-257c-4684-b24a-38d9a8017d30)

**Comment by stilliard** [comment]
If it helps, here's how I use this from Branch Protection rules:

![image](https://github.com/user-attachments/assets/c9552353-2417-4ed1-bcf4-eecc656a8d22)

**Comment by pylapp** [comment]
Seems ok now, I don't understand why for a moment the tool was quite frozen and not status updated.
Maybe some latency issues with GitHub?

You may close this issue then.

Thank you for your quick answer and details!

**Comment by stilliard** [comment]
Hey @pylapp 
Thanks for the update, glad to hear it's working now. 

Yeah there can be a delay with GitHub initially while setting it up sometimes, not sure why but normally after pushing a new pull request or updating one it fixes it. 

Thanks & let me know if there's anything else I can help with on this.
