### ISSUE TITLE
[Security] App has 'write' access to Pull Request

### ISSUE THREAD

**Issue by Evilweed** [stilliard/github-task-list-completed#4]
This app has 'write' access to Pull Request - this is a security issue, and I don't believe it's needed by this app. This app should use `pull_requests: read` instead of `write` so that it can only read missing tasks in Pull Request body - allowing this app to write/modify pull request gives @stilliard possibility to abuse this to affect other people repos.

**EXPECTED BEHAVIOR:**
App has write access only to Github Checks.

**Comment by stilliard** [comment]
Hi @Evilweed , thanks for reporting this. 
Just got back and looking into this right away.

**Comment by stilliard** [comment]
Hi again, thanks for noticing the incorrect listed permission. 
I've now changed this to read only access thanks :+1:
