### ISSUE TITLE
Accept lists with * in addition to -

### ISSUE THREAD

**Issue by leods92** [stilliard/github-task-list-completed#5]
I could make that change if it's something that's accepted (and add some tests for it) :)
Can/should I? :D

**Comment by stilliard** [comment]
Hey @leods92 
Sounds awesome, I didn't even realise GitHub supported the checklists with asterisks, nice catch!

Yer that'd be an awesome contribution if that's ok?
We don't have any tests setup, been meaning to for this anyway so that'd be super useful thanks.

**Comment by leods92** [comment]
Cool ^^
I’ll try to send something this week; it should be quick. :)
