### ISSUE TITLE
feat: Check for tasks in comments

### ISSUE THREAD

**Issue by hitmands** [stilliard/github-task-list-completed#8]
This feature could also be enabled for review's comments.

```yml
Reviewer: "We could use binary search here"
PR Owner: "- [ ] use binary search"
```

```
Github Check: There is one outstanding task at line 12
```

https://github.com/stilliard/github-task-list-completed/blob/f21c6265c997fc37c779f003093c5372871e95dd/index.js#L13

**Comment by stilliard** [comment]
Hi @hitmands I think PR comments would be a great feature to support too, also suggested here: #2

I haven't had chance to review this yet unfortunately but maybe some time over the christmas period.

**Comment by alavkx** [comment]
Just wanted to say thank you. I love this app! We'll be using it in all of our repos at Appcues :)

**Comment by tinydylan** [comment]
+1 My team is migrating from BitBucket server and we really miss this.

**Comment by billsacks** [comment]
@stilliard thank you for developing this nice little app! I also wanted the functionality requested in this issue, though. For my purposes, a command-line tool was suitable. For others who want this functionality via a command-line tool, I'd invite you to check out https://github.com/ESMCI/github-tools. This allows you to show all outstanding todo items in all comments of a PR, with links to the original comments; todos are sorted into required vs. optional, and can be filtered on username.

Example usage:

```
$ gh-pr-query -r esmci/github-tools -p 1 -t
- Do a task from the body's second checklist
  (billsacks at 2020-04-23 19:24:00-06:00, <https://github.com/ESMCI/github-tools/pull/1>)

- Please change "PR" to "Pull Request"
  (billsacks at 2020-04-23 19:25:28-06:00, <https://github.com/ESMCI/github-tools/pull/1#discussion_r414063434>)

- Add a section on Demo deletions
  (billsacks at 2020-04-23 19:25:49-06:00, <https://github.com/ESMCI/github-tools/pull/1#pullrequestreview-399407911>)

- I should do that
  (billsacks at 2020-04-23 19:26:39-06:00, <https://github.com/ESMCI/github-tools/pull/1#issuecomment-618612295>)

- [OPTIONAL] Do a task suggested in the body
  (billsacks at 2020-04-23 19:24:00-06:00, <https://github.com/ESMCI/github-tools/pull/1>)

- [OPTIONAL] Please change "just" to "only"
  (billsacks at 2020-04-23 19:25:28-06:00, <https://github.com/ESMCI/github-tools/pull/1#discussion_r414063434>)
```

**Comment by stilliard** [comment]
Merging this with #2 but will be working on this soon :)

**Comment by stilliard** [comment]
Added a PR for this ref #15 btw.
